version: "3.8"
services:
  sql-server-db:
    container_name: SQLSERVERINSTANCE
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SQL_DB_PASS}
      ACCEPT_EULA: ${SQL_ELUA}