version: "3.8"
services:
  sql-server-db:
    container_name: SQLSERVERINSTANCE
    #for M1 chip base image can be changed to:
    #image: mcr.microsoft.com/azure-sql-edge:latest
    image: mcr.microsoft.com/mssql/server:2022-latest 
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SQL_DB_PASS}
      ACCEPT_EULA: ${SQL_ELUA}
    # TODO: 
    #Identity-service
    #Gateway
    #Api-service
    #front?
    #Service bus